name: lib_discord
description: Discord API wrapper, still under development.
version: 0.0.2-beta1
homepage: https://github.com/KaikyuLotus/discord.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.1
  logging: ^1.0.1

dev_dependencies:
  effective_dart: ^1.3.1
  test: ^1.16.8
